name: pymongo
url: http://api.mongodb.org/python/current/
path: pymongo.inv
---
name: metadriver
url: https://docs.mongodb.org/meta-driver/latest/
path: metadriver.inv
---
name: python
url: https://docs.python.org/2/
path: python2.inv
---
name: mongodb
url: https://docs.mongodb.org/manual/
path: mongodb.inv
---
name: argh
url: https://argh.readthedocs.org/en/latest/
path: argh.inv
...
